// import "./globals.css";
// import { cn } from "@/lib/utils";


// const fontSans = FontSans({
//   subsets: ["latin"],
//   variable: "--font-sans",
// })

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

import "./globals.css"
import { Inter ,Poppins } from "next/font/google";
import { cn } from "@/lib/utils"
import { Weight } from "lucide-react";



const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({subsets : ['latin-ext' ] , weight:["400"]})

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          `min-h-screen bg-background antialiased ${poppins.className}`,
        )}
       >
      {children}
      </body>
    </html>
  )
}
